### ISSUE TITLE
Starter with parcel 2

### ISSUE THREAD

**Issue by icebergMNE** [react-pdf-viewer/starter#23]
Hello, 

I tried updating parcel started to parcel 2, since version 1 is deprecated, but after building the viewer is stuck on loading pdf without any errors.
I can provide the code if needed.

Is there a chance that starter can be updated to support parcel 2? Thank you.

**Comment by phuoc-ng** [comment]
@icebergMNE Parcel v2 is just released a few days ago.
I have updated the [starter](https://github.com/react-pdf-viewer/starter/tree/main/parcel).
